const rl = @import("raylib");
const DB16 = @import("palette.zig").DB16;

pub const CONF = struct {
    pub const VERSION = "alpha2";
    pub const THE_NAME = "P1Xel Editor";
    pub const SCREEN_W = 1280;
    pub const SCREEN_H = 800;
    pub const PALETTES_FILE = "palettes.dat";
    pub const TILES_FILE = "tiles.dat";
    pub const MAX_PALETTES = 128;
    pub const MAX_TILES = 128;
    pub const FONT_DEFAULT_SIZE = 20;
    pub const FONT_BIG = 40;
    pub const CORNER_RADIUS = 0.1;
    pub const CORNER_QUALITY = 2;
    pub const SHADOW = 4;
    pub const FRAME = 2;
    pub const SPRITE_SIZE = 16; // The actual sprite dimensions (16x16 pixels)
    pub const GRID_SIZE = 32; // How large each pixel appears on screen
    pub const CANVAS_SIZE = SPRITE_SIZE * GRID_SIZE;
    pub const CANVAS_FRAME_SIZE = 16;
    pub const CANVAS_X = 0;
    pub const CANVAS_Y = 64;
    pub const POPUP_DIM = 128; // 0-255 background dim
    pub const COLOR_BG = DB16.DARK_GRAY;
    pub const COLOR_PRIMARY = DB16.WHITE;
    pub const COLOR_SECONDARY = DB16.LIGHT_GRAY;
    pub const COLOR_CROSSHAIR = DB16.LIGHT_GRAY;
    pub const COLOR_YES = DB16.GREEN;
    pub const COLOR_NO = DB16.RED;
    pub const COLOR_OK = DB16.DARK_GRAY;
    pub const COLOR_POPUP = DB16.NAVY_BLUE;
    pub const COLOR_POPUP_MSG = DB16.WHITE;
    pub const COLOR_SHADOW = DB16.BLACK;
    pub const COLOR_LIGHT = DB16.WHITE;
    pub const COLOR_MENU_NORMAL = DB16.LIGHT_GRAY;
    pub const COLOR_MENU_SECONDARY = DB16.DARK_GRAY;
    pub const COLOR_MENU_HIGHLIGHT = DB16.ORANGE;
    pub const COLOR_MENU_DANGER = DB16.RED;
    pub const VFX_SNOW_MIN = 4;
    pub const VFX_SNOW_MAX = 64;
    pub const VFX_SNOW_ALPHA = 0.0025;
    pub const VFX_SNOW_SPEED_MIN = 0.2;
    pub const VFX_SNOW_SPEED_MAX = 1.5;
};
